Rework file I/O in mesh converters for thread-safety
MPAS-Dev/MPAS-Tools pull request #437
Opened 2021-07-29 19:27 UTC by dengwirda

This PR reworks the way the C++ `MpasMeshConverter.x` and `MpasCellCuller.x`, as well as the MPAS-Tools `conversion.py` wrapper, handles file I/O to eliminate the need to change into local directories to account for hard-coded relative file names (e.g. `graph.info`).

Eliminating the `os.getcwd()` + `os.chdir()` pattern in `conversion.py` makes these routines thread-safe, allowing them to be called across parallel threads.

2021-07-29 19:35 UTC, dengwirda commented
To run additional tests (attached):
```
cd conda_package
conda env create -y -n mpas_tools_dev --file dev-spec.txt
conda activate mpas_tools_dev
python -m pip install -e .
cd ..
cd mesh_tools/mesh_conversion_tools
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=Debug ..
make
make install
```
```
python test_sphere.py
python test_planar.py
```
[test_mesh_converter.zip](https://github.com/MPAS-Dev/MPAS-Tools/files/6903180/test_mesh_converter.zip)

2021-07-29 19:56 UTC, xylar requested changes
For now, just requesting a few formatting fixes.  I'll test this in compass tomorrow.  Thanks for the nice example tests and instructions!

2021-07-29 19:56 UTC, xylar commented on mesh_tools/mesh_conversion_tools/mpas_cell_culler.cpp
> +    string out_fext = "";
```suggestion
	string out_path = "";
	string out_file = "";
	string out_fext = "";
```
These should be tabs, not spaces, to be consistent with existing file formatting (ugly as it may be)

2021-07-29 19:56 UTC, xylar commented on mesh_tools/mesh_conversion_tools/mpas_cell_culler.cpp
> +    file_part(out_name, out_path, out_file, out_fext);
```suggestion
	file_part(out_name, out_path, out_file, out_fext);
```
Again, tabs...

2021-07-29 19:56 UTC, xylar commented on mesh_tools/mesh_conversion_tools/mpas_cell_culler.cpp
> +    string out_fext = "";
The same formatting issue is also in `mpas_mesh_converter.cpp`.

2021-07-29 19:58 UTC, dengwirda commented on mesh_tools/mesh_conversion_tools/mpas_cell_culler.cpp
> +    file_part(out_name, out_path, out_file, out_fext);
Ah, right... no worries!

2021-07-29 19:58 UTC, xylar commented
@mgduda, @akturner, @matthewhoffman and @mark-petersen, this work is needed as part of working on supporting parallel tasks via Parsl.  If we make meshes in parallel with threads, it turns out that we can't be doing `chdir` type operations because these aren't thread-safe in python.

2021-07-29 20:00 UTC, xylar commented
@dengwirda, could you add to the PR description that the approach for modifying the C++ code is to use the directory of the output file also as the directory for the other files (e.g. graph.info)?  I think that's missing.

2021-07-30 05:00 UTC, matthewhoffman approved these changes
I'm just going to approve by inspection.  This makes sense and the changes look appropriate.  Thank for working on this Darren.

2021-07-30 10:40 UTC, xylar commented
@dengwirda, I tested this in `compass` on both my Linux laptop and Chrysalis.  I needed to build the conda package (so that conda-forge compilers were used instead of system compilers) rather than following the instructions above, which used system compilers.  When I did that, I got bit-for-bit identical results with the ocean nightly test suite for all tests.

2021-07-30 15:33 UTC, akturner approved these changes
Built and ran successfully for me

2021-08-02 14:19 UTC, mark-petersen approved these changes
I compiled the c++ MpasCellCuller and MpasMeshConverter on grizzly with both gnu and intel and tested them individually with a QU240 mesh. Everything appears to work fine. Thanks!

2021-08-03 16:13 UTC, mgduda commented on mesh_tools/mesh_conversion_tools/mpas_mesh_converter.cpp
> +    file_part(out_name, out_path, out_file, out_fext);
If we would like to match existing formatting, the spaces here should be changed to a tab.

2021-08-03 16:17 UTC, mgduda requested changes
I'll second @xylar's suggestion to fix the whitespace in `mpas_cell_culler.cpp` and `mpas_mesh_converter.cpp`.

2021-08-20 13:01 UTC, xylar commented on mesh_tools/mesh_conversion_tools/mpas_mesh_converter.cpp
> +    string out_fext = "";
```suggestion
	string out_path = "";
	string out_file = "";
	string out_fext = "";
```

2021-08-20 13:01 UTC, xylar commented on mesh_tools/mesh_conversion_tools/mpas_mesh_converter.cpp
> +    file_part(out_name, out_path, out_file, out_fext);
```suggestion
	file_part(out_name, out_path, out_file, out_fext);
```

2021-08-20 13:03 UTC, xylar commented
@mgduda, I went ahead and fixed the white space since it seems like @dengwirda hasn't had time.  Could you give it another look to make sure you're okay with the changes otherwise?

2021-08-20 13:05 UTC, xylar approved these changes
Approving now that white space issues are fixed.

2021-09-22 15:56 UTC, xylar commented
@mgduda, is this something you might have time to try out soon?  If so, the timing would be good with other fixes we want to make for another MPAS-Tools release.

2021-09-22 16:22 UTC, mgduda approved these changes
Sorry about the delay!

2021-09-22 16:23 UTC, xylar commented
Thanks @mgduda!

2021-09-22 16:23 UTC, merged