Update CISM script to be compatible with python 3
MPAS-Dev/MPAS-Tools pull request #444
Opened 2021-10-04 19:34 UTC by hollyhan

This merge
- fixes proj syntax.
- takes options for data rank (1 or 2).

2021-10-04 19:36 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +
fix white space

2021-10-04 19:38 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +
```suggestion
```

2021-10-04 19:42 UTC, hollyhan commented
@matthewhoffman @xylar - This is ready to review. Thanks :)

2021-10-04 20:15 UTC, xylar commented
@matthewhoffman or @hollyhan, does either of you have an example CISM file handy that I could use to test this on?

2021-10-04 20:48 UTC, matthewhoffman commented
@hollyhan & @xylar , this looks great - thanks both of you for working through the details of updating this.

@trhille , do you have a simple regular grid GIS or AIS dataset that could be used for testing this regridding script?  We call it 'cism' format here, but we don't actually use CISM files anymore.

2021-10-04 20:49 UTC, xylar commented
@matthewhoffman and @trhille, @hollyhan sent me a file to work with so I'm set.

2021-10-04 20:57 UTC, matthewhoffman requested changes
@hollyhan & @xylar , thanks for working on updating this script.  I made a few comments below.  I'm not sure if we will use this enough to justify a lot of work on small details, but it's also a good first PR exercise!

2021-10-04 20:57 UTC, matthewhoffman commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +x1 = fin.variables['x'][:]
the `x1` and `y1` dimension variable names were used in CISM, and for awhile we primarily were using CISM files as source datasets.  At this point we don't do that anymore and instead use a range of regular ice sheet data source files.  I believe they typically have dimension variable names of `x` and `y`, so we could just change that everywhere in this script.  We could also go and change the filename as well, e.g. `create_SCRIP_file_from_planar_rectangular_grid.py`

2021-10-04 20:57 UTC, matthewhoffman commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +# HH: the above dictionary for projections are commented out, and modified PROJ strings (compatible with Pyproj v3) are added below
You can go ahead and delete the commented version that is no longer supported.  Thanks for updating to the new pyproj requirements.

2021-10-04 20:57 UTC, matthewhoffman commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
>  import pyproj
Is the plain import of `pyproj` still needed?  If not, go ahead and delete it.

2021-10-04 20:57 UTC, matthewhoffman commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
@hollyhan , do you think it is useful to leave this uncommented?  Or would it be better to re-comment it?

2021-10-04 21:02 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
I personally think you should add an optional `--plot` flag and call this if `--plot` is present.  But it should be commented out if you don't want to do that.

2021-10-04 21:03 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +#grid_dims[:] = [nx , ny] # HH: for RANK 2 data
I don't think this comment is needed.  It is clear from the if/else above.

2021-10-04 21:05 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +    grid_dims[:] = [nx , ny]
It's always best to have `if`/`elseif`/`else`.  This way, there is a clear error message when a wrong parameter value is given:
```suggestion
if int(options.gridRank) == 1:
    print('grid dims is nx*xy')
    grid_dims[:] = (nx * ny) # for RANK 1 data
elif int(options.gridRank) == 2:
    print('grid dims is nx,xy')
    grid_dims[:] = [nx , ny]
else:
    raise ValueError(f'gridRank must be 1 or 2 but {options.gridRank} was given.') 
```

2021-10-04 21:06 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +    grid_dims[:] = [nx , ny]
Oh, I see, you do this above...

2021-10-04 21:07 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +    exit()
A more typical way to do this would be:
```suggestion
else:
    raise ValueError(f'grid rank value is invalid: valid options are 1 or 2 but {options.gridRank} was given.') 
```

2021-10-04 21:09 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +x1 = fin.variables['x'][:]
I would strongly support the name change if it isn't being used for CISM grids.  You could also add `-x` and `-y` flags that default to `x` and `y` if you thought you would ever need the `x1` and `y1` versions again.

2021-10-04 21:12 UTC, xylar commented
We include the [`create_SCRIP_file_from_MPAS_mesh.py`](https://github.com/MPAS-Dev/MPAS-Tools/blob/master/mesh_tools/create_SCRIP_files/create_SCRIP_file_from_MPAS_mesh.py) in the `mpas_tools` conda package.  Would it be helpful to include this script, too?  If so, it should be added below here:
https://github.com/MPAS-Dev/MPAS-Tools/blob/master/conda_package/setup.py#L64

@matthewhoffman, what do you think?

2021-10-04 22:25 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
I now remember that I commented this section out to do quick testing of the code without plotting. I could revise it and add an optional --plot flag as Xylar suggests.

2021-10-04 22:27 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +    exit()
Oh, very cool. Got it! Thanks, Xylar :)

2021-10-05 18:52 UTC, matthewhoffman commented
@xylar , now that you mention it, yes it would be useful to include this as well in mpas-tools package.  The use case I am thinking of is when we need to do conservative remapping from ice sheet source datasets to MALI meshes in compass.  We have historically just done these as one-offs but it would be valuable to have the ability within compass.  Should we add that package change to this PR in an additional commit?  (after the script name change)

2021-10-05 18:59 UTC, xylar commented
> Should we add that package change to this PR in an additional commit? (after the script name change)

Yes, I think that makes sense.  No need to keep it separate.

2021-10-06 20:13 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +x1 = fin.variables['x'][:]
I've changed the variable names 'x1' and 'y1' to 'x' and 'y'

2021-10-06 20:20 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
Now that I'm going through the revision, I actually think it would be useful to leave this whole block uncommented because it's a useful checking tool for output scrip files. I realize I commented the block out because I was doing a number of quick tests to see if the code runs well after some edits, but then I never remembered to uncommented it after.

2021-10-06 20:25 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
Hmm, in your version of the code (in green) the plotting isn't commented out.  So I'm guessing you uncommented the plotting to get some plots to see what is going on.

Are you suggesting just switching back to the commented-out version?  I think that was @matthewhoffman's suggestion.  I still think it would be a better practice to add flags to the arguments rather than expecting users to modify the script.  For one thing, modifying the script within a conda environment is both hard and not a good practice. So I still advocate adding a command-line flag `--plot` and putting an `if arg.plot:` statement around this plotting code (except the `import`, which needs to go to the top of the file).

2021-10-06 20:38 UTC, hollyhan commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +import matplotlib.pyplot as plt
Okay, I'm definitely getting my memory mixed up! Okay, I will include a command-line plot! I've also moved the import matplotlib part to the top of the file.

2021-10-06 21:27 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
> +parser.add_option("--plot", dest="plot", help="destination grid points are plotted if 'True'. Default is 'False'", default=False)
There's a slightly cleaner way to handle this:
https://docs.python.org/3/library/optparse.html#handling-boolean-flag-options

```suggestion
parser.add_option("--plot", dest="plot', action="store_true", help="If this flag is used, destination grid points are plotted")
```

2021-10-06 22:50 UTC, xylar commented
> I'm not sure how to start conversation on the new page 

@hollyhan, to start a conversation about a part of the code, you go to "Files changed" at the top of the page, scroll down to the code changes, move your mouse over to the left margin (before the line numbers) so you see a blue plus sign, and select the line(s) you want to discuss.  Then, a small conversation window will pop up.  You can use the "Insert a suggestion" button (a page with a +/- on it) to make suggestions about changes to the code like I've been doing.

Some other handy code formatting tips for GitHub are here:
https://guides.github.com/features/mastering-markdown/
These also work (pretty well) on Slack.

2021-10-07 01:47 UTC, xylar commented
@hollyhan, I think your last commit added a new file named `create_SCRIP_file_from_planar_rectangular_grid.py` but didn't delete the one with the old name.  Could you do:
```
git rm mesh_tools/create_SCRIP_files/create_SCRIP_file_from_CISM_mesh.py
git commit
git push ...
```
That should take care of it.

2021-10-07 22:04 UTC, xylar commented on mesh_tools/create_SCRIP_files/create_SCRIP_file_from_planar_rectangular_grid.py
> +    plt.show()
This is super picky since this is just for debugging but maybe plot the two figures and then show them both:
```suggestion
    plt.figure(1)
    plt.plot(grid_center_lon[i], grid_center_lat[i], 'o')
    plt.plot(grid_corner_lon[i, 0], grid_corner_lat[i, 0], 'kx')
    plt.plot(grid_corner_lon[i, 1], grid_corner_lat[i, 1], 'bx')
    plt.plot(grid_corner_lon[i, 2], grid_corner_lat[i, 2], 'cx')
    plt.plot(grid_corner_lon[i, 3], grid_corner_lat[i, 3], 'gx')

    #plot all points
    plt.figure(2)
    plt.plot(grid_center_lon[:], grid_center_lat[:], 'bo')
    plt.plot(grid_corner_lon[:], grid_corner_lat[:], 'g.')
    plt.show()
```

2021-10-08 17:45 UTC, hollyhan commented
Hi @xylar , yes! Please go ahead and push the change to the branch - you won't be stepping on anyone's toes! Thanks for checking with me.

2021-10-08 22:59 UTC, xylar commented
@hollyhan, the changes I made are on my work laptop so I'll push them on Monday.  Thanks for the latest update.

2021-10-12 05:08 UTC, xylar commented
@hollyhan, let me know if you've run the extra steps (`ESMF_RegridWweightGen` or `ncremap`) that @matthewhoffman mentioned and if they were successful.  If so, I'll merge.

2021-10-12 16:27 UTC, merged

2021-10-12 16:28 UTC, xylar commented
Thanks again @hollyhan and @matthewhoffman!