Add analysis script for plotting regional stats
MPAS-Dev/MPAS-Tools pull request #471
Opened 2022-08-23 18:56 UTC by matthewhoffman

This script is modified from the global stats script.  It plots three
different figures, each with subpanels for each region.  The first is
overall mass change statistics.  The second is the grounded mass
balance, and the third is the floating mass balance.  It is possible to
plot up to four runs, each with a different linestyle, but because of
the number of lines on each plot, plotting multiple runs is not pretty.

2022-08-24 20:45 UTC, trhille requested changes
@matthewhoffman This is great. I have requested some changes to reduce redundancy and increase readability, but functionally everything is there. The only functional issue is that the legend doesn't show up if the last subplot is empty (i.e., if there is an odd number of regions).

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +#!/usr/bin/env python
Note that the name of this script follows a difference scheme from plot_globalStats.py. For consistency it's probably better to call it plot_regionalStats.py.

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +nrow=4
Can we either have the script calculate the necessary number of rows and columns or have these as user input options?

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +# Set up Figure 2: grd MB
can you change "grd MB" to "grounded mass balance"

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +# Set up Figure 3: flt MB
can you change "flt MB" to "floating mass balance"

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +for reg in range(nRegions):
Instead of a separate loop for each figure, what about using nested loops over figures and regions?

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +for reg in range(nRegions):
e.g.,:
```
for ax in [axs1, axs2, axs2]:
    for reg in range(nRegions):
```

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +        sys.exit(f"ERROR: Number of regions in file {fname} does not match number of regions in first input file!")
This will be triggered for any input file, not just the first one, right?

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +    if options.units == "m3":
Can we loop over a few list of variables based on their units instead of having ten separate instances of this if-statement?

2022-08-24 20:45 UTC, trhille commented on landice/output_processing_li/plot_regional_stats.py
> +axs1.flatten()[-1].legend(loc='best', prop={'size': 6})
The legend doesn't show up if the last subplot is empty. For example, I'm using 27 regions with nrow = 7 and nrow = 4, so the -1th subplot has nothing in it. Can we put the legend in the first subplot to avoid that?

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +include the basin info and gamma0 so it can dropped directly into a streams file to run with.
```suggestion
includes the basin info and gamma0 so it can dropped directly into a streams file to run with.
```

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +           # 1 -  Linear interpolation of the thermal forcing on the ice draft depth :
no # 2?

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    melt = gamma0 * coef * slope * (TFdraft + deltaT) * np.absolute(meanTFcell + deltaT) # m/yr
Are you sure we want `np.absolute(meanTFcell + deltaT)`? Conceivably meanTFcell + deltaT could be negative, in which case we probably don't want it to end up being positive, right? Instead, do we want `np.maximum(meanTFcell + deltaT, 0.)`?

2022-09-13 22:43 UTC, trhille commented on landice/output_processing_li/plot_globalStats.py
> +if options.plotChange:
However, while we are changing this, we might as well switch over to using f-strings.

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    if False:
Let's have a `-p` option to determine whether to plot or not.

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +ISMIP6basinInfo = {
These are from Rignot et al. (2008) and Rignot et al. (2013)? Needs a comment.

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    bestdT[r] = np.interp(ISMIP6basinInfo[rNamesOrig[r]]['shelfMelt'][0], allMelts[:,r], dTs)
```suggestion
    # Find dT that results in Rignot et al. (2008) melt rate for each basin
    bestdT[r] = np.interp(ISMIP6basinInfo[rNamesOrig[r]]['shelfMelt'][0], allMelts[:,r], dTs)
```

2022-09-13 22:43 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    regionCells[regionCellMasks[:,r]==1] = r+1
Why is this done?

2022-09-13 22:45 UTC, trhille commented
@matthewhoffman, I've reviewed the two new pre-processing scripts. I still need to re-review plot_regional_stats.py, but I wanted to look those two over to test out https://github.com/MALI-Dev/E3SM/pull/48

2022-09-15 23:16 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    melt = gamma0 * coef * slope * (TFdraft + deltaT) * np.absolute(meanTFcell + deltaT) # m/yr
That's by design.  It allows you to get freeze-on when TF<0.  If you look at the PIGL plots in the Jourdain paper, you can see negative melt rates in some places.

2022-09-15 23:18 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    melt = gamma0 * coef * slope * (TFdraft + deltaT) * np.absolute(meanTFcell + deltaT) # m/yr
Yes that makes sense now. I had tunnel vision on that last term.

2023-01-04 03:21 UTC, matthewhoffman commented on landice/output_processing_li/plot_regional_stats.py
> +for reg in range(nRegions):
At this point (might not have been the the case when you reviewed this in August...) there are enough differences between figures that I think it's easier to leave as separate chunks of code for each.

2023-01-04 03:23 UTC, matthewhoffman commented on landice/output_processing_li/plot_regional_stats.py
> +        sys.exit(f"ERROR: Number of regions in file {fname} does not match number of regions in first input file!")
Yes, it will be triggered for any input file.  It doesn't seem possible to ensure the regions are the same regions, but we can at least err if the number of regions doesn't match.

2023-01-04 03:41 UTC, matthewhoffman commented on landice/mesh_tools_li/adjust_iceshelf_geometry.py
> +for c in range(nCells):
I've added a comment to the code explaining this step.

2023-01-04 03:45 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    if False:
In general, I don't think we will want to plot a melt map for every dT considered, but it can be useful for debugging, etc.  I added a comment to that effect.

2023-01-04 03:54 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    regionCells[regionCellMasks[:,r]==1] = r+1
the ISMIP6 region mask is a single integer field, while regionCellMasks is a separate 0/1 mask for each region, so this converts the latter to the former.  I added a comment to the code about it.

2023-01-04 03:59 UTC, matthewhoffman commented
@trhille , now that things have settled down with our ISMIP6 workflow, I finally cleaned up this PR.  I deleted a few scripts that did not end up being relevant, and I responded to review comments and did general cleanup with the others.  I responded directly to comments above for which I had a response.  For those without a response, I simply made the changes.  

I realize there is a lot to review in this PR; if you prefer this be broken into a couple PRs for different scripts, I can do that.  Also, there is no real rush to get this re-reviewed and merged, but it would be nice to check this off and have it on master before too much time goes on.  I'll leave it up to you regarding the level of detail you think further review warrants.

2023-01-17 23:41 UTC, trhille requested changes
@matthewhoffman, this is great! I have a few fairly minor comments to address before we merge this. Thanks for all your hard work on this.

2023-01-17 23:41 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +TFocean = ff.variables['ismip6shelfMelt_3dThermalForcing'][0,:,:]
We might want to either make a note in the header docstring that this operation is on the zeroth time level of the forcing file, or add the time level as an optional user input that defaults to 0. I can see wanting to use this script on the year 2015, for example, with a forcing file that starts in 1950.

2023-01-17 23:41 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    meanSlopeFactor = ((1.0 + 900.0 * slope[ind]) * areaCell[ind]).sum() / areaCell[ind].sum()
Add comments describing where `meanSlopeFactor` and `meanSlopeFactor2` calculations come from.

2023-01-17 23:41 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    mean_TF = 0.0
This definition is never used.
```suggestion

```

2023-01-17 23:41 UTC, trhille commented on landice/output_processing_li/plot_calving_calibration.py
> +# Set up Figure 2: calving
```suggestion
# Set up Figure 4: calving
```

2023-01-17 23:41 UTC, trhille commented on landice/output_processing_li/plot_regionalStats.py
> +ISMIP6basinInfo = {
We should have a note in the header docstring that explains that currently the script is only useful for whole Antarctic runs. Maybe in a future PR we can add an optional input variable that points to a file that contains observational data, so this can be used for any arbitrary configuration, with or without observations plotted.

2023-01-17 23:41 UTC, trhille commented on landice/output_processing_li/plot_regionalStats.py
> +        axs4.flatten()[r].plot(yr, areaTot[:,r] - areaTot[0,r], label=("total area" if addToLegend else '_nolegend_'), linestyle=sty, color='k')
Definition of `lbl` in figures above is better practice than the repetition of `label=("total area" if addToLegend else '_nolegend_')` here.

2023-01-17 23:42 UTC, trhille commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +ISMIP6basinInfo = {
This would also be useful for generalizability.

2023-02-01 21:42 UTC, matthewhoffman commented on landice/mesh_tools_li/bulldoze_missing_troughs.py
> +# Define maximum and minimum water column thickness along tough centerline
I like leaving them here, because they go along with the point definitions to be modified.  Also note that the final trough is hardcoded to use different values.  I added a note to the docstring directing a user to that part of the code.

2023-02-01 21:47 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +ISMIP6basinInfo = {
Yeah, it would be nice to put it some place central so we aren't repeating it, but I punted on dealing with that for now.  If all this was in the conda package, we could use it, but for the scripts as written, the most robust thing seemed to be to include it everywhere.

2023-02-01 21:49 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +TFocean = ff.variables['ismip6shelfMelt_3dThermalForcing'][0,:,:]
I added a note in the docstring and the argument description for the TF file.  I imagine in general we'll want to apply this to a climatology rather than a specific year, but we can add an option if more flexibility is desired.

2023-02-01 21:52 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    meanSlopeFactor = ((1.0 + 900.0 * slope[ind]) * areaCell[ind]).sum() / areaCell[ind].sum()
I deleted all the slope stuff, because that branch never survived in MALI.  The slope version of this script will be in the history of this branch if we ever need it again.

2023-02-01 21:52 UTC, matthewhoffman commented on landice/mesh_tools_li/tune_ismip6_melt_deltat.py
> +    mean_TF = 0.0
removed

2023-02-01 21:54 UTC, matthewhoffman commented on landice/output_processing_li/plot_regionalStats.py
> +ISMIP6basinInfo = {
note added

2023-02-01 21:56 UTC, matthewhoffman commented on landice/output_processing_li/plot_regionalStats.py
> +        axs4.flatten()[r].plot(yr, areaTot[:,r] - areaTot[0,r], label=("total area" if addToLegend else '_nolegend_'), linestyle=sty, color='k')
In this case there'd be 3 different `lbl` variables defined before the for loop and used inside it, so I left this easier to read version.

2023-02-01 21:58 UTC, matthewhoffman commented
@trhille , I pushed another cleanup commit addressing your latest round of review.  I think this should be ready to go now.

2023-02-01 23:01 UTC, trhille approved these changes
Thanks, @matthewhoffman, for this great set of tools!

2023-02-01 23:07 UTC, merged