Add post-processing scripts for the ISMIP6 experiment
MPAS-Dev/MPAS-Tools pull request #476
Opened 2022-10-24 16:03 UTC by hollyhan

This PR adds scripts that post-processes MALI state and flux output variables in the format required by the ISMIP6 team. 
In the previous (first) participation of the MALI team to the ISMIP6-2100 experimental protocol, post-processing MALI outputs involved many steps of manual running of several python scripts and `nco` commands, which can be tedious and exposed to potential human errors. The scripts here have been written to improve the automation of the workflow and thus reduce the room for making mistakes.

2022-10-24 16:15 UTC, hollyhan commented
Hi @matthewhoffman, the PR has been opened now! 
If it helps (since there are many flags one needs to provide), here is the sample command line I used to run the scripts:
```
./post_process_mali_to_ismip6.py -i_state output_state_2015.nc -i_flux output_flux_all.nc -i_init AIS_8to30km_r01_20220906.smooth3.basinsFineTuned.nc --mali_mesh_name AIS_8to30km --ismip6_grid_file UKESM1-0-LL_temperature_8km_x_60m.nc  -e ctrl -g globalStats.nc  -p /Users/hollyhan/ISMIP6-PostProcessing/files_states_processed/ 
```
Note that you might run into errors running the script if the MALI initial and output (state and flux) files that you use to test this PR are missing the variables required by the ISMIP6. (There are some lines that I commented out because the output files I was using did not have all of the variables required by the ISMIP6.).

2022-10-24 20:10 UTC, matthewhoffman requested changes
@hollyhan , thank you so much for getting these processing scripts organized and cleaned up.  This will be a huge help going forward.  In my comments, I've tried to balance having clean, reusable code with the fact that it's possible we won't be running this frequently or any time soon (only when ISMIP activities occur).  But I'm assuming there may be future ISMIP activities in the coming years that we'll want to participate in, so we should aim for this to be flexible beyond the current set of experiments, where possible without too much trouble.  

Most of comments are pretty minor, but one fairly big one I see is that I think it will be important to be able to point the scripts to a directory without having to ncks all the individual output files together first.  However, that change is fairly fundamental, so I'll follow up with you about if/how we can handle that.

2022-10-24 20:10 UTC, matthewhoffman commented on landice/output_processing_li/process_state_variables.py
> +        # take the average of the flux variables
These should ideally be a weighted average: `(var[:]*deltat[:]).sum()/deltat[:].sum()` for the indices of each year.

2022-10-24 20:10 UTC, matthewhoffman commented on landice/output_processing_li/process_flux_variables.py
> +    check_call(command)
This time we are writing one flux file per year, so I don't think we need to do any of this.  We simply need to open each file, perform the weighted average over all time levels in that file, and save the result.

2022-10-24 21:07 UTC, hollyhan commented on landice/output_processing_li/process_flux_variables.py
> +    nCells=10
remove

2022-10-24 21:09 UTC, hollyhan commented on landice/output_processing_li/process_flux_variables.py
> +        file_flux_on_cell)  # writing out to a netCDF file seems to be needed to save the newly added variable `fluxAcrossGroundingLineCell`.
clean up

2022-10-25 02:36 UTC, matthewhoffman commented on landice/output_processing_li/post_process_mali_to_ismip6.py
> +                        required=False, help="mpas output flux variables")
After our discussion, we'll defer this to a future PR if needed.

2022-10-25 02:50 UTC, matthewhoffman commented on landice/output_processing_li/process_flux_variables.py
> +        file_flux_on_cell)  # writing out to a netCDF file seems to be needed to save the newly added variable `fluxAcrossGroundingLineCell`.
I'm commenting the calving chunk for now.  We can remove if we add the calving calculation directly to MALI.  Or clean it up if we don't.

2022-10-25 15:13 UTC, matthewhoffman commented on landice/output_processing_li/process_state_variables.py
> +        if not ismip6_var_name == 'sftgif':
ISMIP6 protocol states: "All "missing data" must be assigned the single-precision floating point value of 1.e20. Fields should be undefined outside the ice mask."  So I'm leaving as is.

2022-11-01 16:20 UTC, trhille reviewed
@matthewhoffman, the changes in L188–219 in `process_flux_variables.py` make sense to me for the `restore_calving_front` case. I marked a few places where I think commented legacy code should be removed for clarity.

2022-11-01 16:20 UTC, trhille commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +    # This part seems to have been used to get `edgeMask`
Can we delete this commented section?

2022-11-01 16:20 UTC, trhille commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +                # if ((edgeMask[0, edgeId[j]] & 16) / 16 and (edgeMask[0, edgeId[j]] & 4) / 4):  # uncomment this line and indent L197 once edgeMask is acquired.
can we delete?

2022-11-02 16:11 UTC, matthewhoffman commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +    # This part seems to have been used to get `edgeMask`
Yes, done in ae2ad7d

2022-11-02 16:11 UTC, matthewhoffman commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +                # if ((edgeMask[0, edgeId[j]] & 16) / 16 and (edgeMask[0, edgeId[j]] & 4) / 4):  # uncomment this line and indent L197 once edgeMask is acquired.
yes, done in ae2ad7d

2022-11-22 16:03 UTC, trhille reviewed
@matthewhoffman, I've gone through `clean_flux_fields_before_time_averaging()` and it makes sense to me. I made a few minor comments for clarity.

2022-11-22 16:03 UTC, trhille commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +                    deltat[t]    # units of kg / m2 / s
The units here are not yet kg /m2/s, but m/s

2022-11-22 16:03 UTC, trhille commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +            calvingFluxArray[t,:] += thresholdFlux[t,:]
```suggestion
            calvingFluxArray[t,bdyIndices] += thresholdFlux[t,bdyIndices]
```
This should amount to the same thing, but I think it's safer than using : indexing.

2022-11-29 15:55 UTC, matthewhoffman commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +            calvingFluxArray[t,:] += thresholdFlux[t,:]
Changed

2022-11-29 15:56 UTC, matthewhoffman commented on landice/output_processing_li/ismip6_postprocessing/process_flux_variables.py
> +        ind = np.nonzero(floatingBasalMassBalApplied[t,:]/rho_i < -1.0)[0]
Yes, the 0 index is to get the first (and only) tuple of actual values.  I double checked that it returns a list longer than 1 when it should.

2022-12-08 20:42 UTC, matthewhoffman approved these changes

2022-12-08 21:04 UTC, merged