Update plot_maps.py for landice plotting
MPAS-Dev/MPAS-Tools pull request #504
Opened 2023-04-18 21:44 UTC by trhille

This merge provides several updates for the landice tool plot_maps.py:
1. It adds the ability for the user to define the range of values plotted using the new `--vmin` and `--vmax` arguments.
2. It adds reasonable bounds on velocities for plotting purposes.
3. It provides the ability to plot mesh variables that have no time dimension, such as `gridSpacing`, `areaCell`, etc.

2023-04-18 21:47 UTC, trhille commented
Testing
-------
On Cori:
`plot_maps -r $CFS/piscees/MALI_input_files/AIS_4to20km_r01/AIS_4to20km_r01_20220907_Bedmap2_surface.nc -v bedTopography,gridSpacing`

![image](https://user-images.githubusercontent.com/17446278/232912460-29365bad-d294-4267-97af-9c4a9f4723dd.png)

2023-04-18 22:51 UTC, xylar commented
Don't worry about the failing tests. They're nothing to do with you. They're something I've tried to get fixed on conda-forge but I'm having trouble getting a response.

2023-04-20 14:59 UTC, matthewhoffman requested changes
@trhille , these look like useful additions.  A few minor comments you can take or leave.

2023-04-20 14:59 UTC, matthewhoffman commented on landice/output_processing_li/plot_maps.py
> +                    help="minimum value(s) for colorbar(s)")
```suggestion
                    help="minimum value(s) for colorbar(s) (list separated by commas; no spaces)")
```

2023-04-20 15:07 UTC, trhille commented
@matthewhoffman, thanks for the review! I addressed your requested changes in [02119d7](https://github.com/MPAS-Dev/MPAS-Tools/pull/504/commits/02119d7dbb80f463e5011017419896486c348fdb).

2023-04-20 15:44 UTC, merged