Extrapolate landice variable
MPAS-Dev/MPAS-Tools pull request #576
Opened 2024-07-09 18:04 UTC by trhille

Add a script to extrapolate landice variables into regions of missing or invalid data using nearest-neighbor or inverse-distance weighted methods.

2024-07-09 19:53 UTC, xylar commented
@trhille, CI is breaking for reasons unrelated to your script.  Someone accidentally released `matplotlib` 3.9.0 on conda-forge a few days back and did a bunch of upgrading to support it.  It turned out they jumped the gun and they moved that release off the main conda-forge channel so now it can't be installed without a lot of extra hassle.  I was hoping the actual release would happen but that also doesn't seem to have happened.

Anyway, I'll fix it if it becomes critical before they actually release the new version.

2024-07-09 19:57 UTC, trhille commented
Thanks, @xylar. This script has been lying around on a branch for years, and we decided that it has ended up with enough use cases that we'll merge it, but it's not at all time-sensitive.

2024-08-01 09:18 UTC, xylar commented
I'm going to close and re-open to cause CI to restart.

2024-08-19 15:04 UTC, matthewhoffman requested changes
@trhille , thanks for formalizing this script.  I have a few comments - feel free to take or leave.  The script works as-is and I don't want to drag this out.

2024-09-09 17:28 UTC, trhille commented on landice/mesh_tools_li/extrapolate_variable.py
> +        keepCellMask *= (varValue < 1.e12)
I think it's safe, but will add it as a constant at the top of the script as with the densities.

2024-09-09 17:50 UTC, trhille commented on landice/mesh_tools_li/extrapolate_variable.py
> +        groundedMask = (thickness > (-1028.0 / 910.0 * bed))
Good catch. I have now changed this to raise an exception with a helpful message if thickness and/or bedTopography are missing. Addressed in https://github.com/MPAS-Dev/MPAS-Tools/pull/576/commits/8f7ef92d3e20cdebe603461440cd1977ce921e24.

2024-09-09 17:50 UTC, trhille commented on landice/mesh_tools_li/extrapolate_variable.py
> +        keepCellMask *= (varValue < 1.e12)
Addressed in https://github.com/MPAS-Dev/MPAS-Tools/pull/576/commits/8f7ef92d3e20cdebe603461440cd1977ce921e24

2024-09-09 18:11 UTC, matthewhoffman approved these changes

2024-09-09 18:11 UTC, merged